services:
  odoo17_app:
    image: odoo:17.0
    container_name: odoo17_app
    environment:
      HOST: odoo17_db
      USER: odoo
      PASSWORD: odoo_secure_pass
    ports:
      - "8069:8069"
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo_net
    restart: unless-stopped

volumes:
  odoo_web_data:
    name: odoo_deployment_ar_odoo_web_data
    external: true

networks:
  odoo_net:
    name: odoo_deployment_ar_odoo_net
    external: true
