[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_secure_pass
db_name = odoo17
admin_passwd = admin
logfile = /var/log/odoo/odoo.log
log_level = info
workers = 0
max_cron_threads = 1
list_db = True
chrome_path = /usr/bin/google-chrome-stable
