[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = odoo17_db
db_port = 5432
db_user = odoo
db_password = odoo_secure_pass
db_name = False
admin_passwd = admin
logfile = /var/log/odoo/odoo.log
log_level = info
