{
    'name': 'الرواتب الحكومية — دورة الصرف الشهرية',
    'summary': 'C-PR-04: Employee salary file, monthly payroll run, Form 132 ع.ح, rewards, register 129 سايرة (FR-8..15)',
    'version': '17.0.1.3.0',
    'category': 'الخدمات الحكومية التجريبية/الرواتب',
    'author': 'Enterprise Solutions Demo',
    'license': 'LGPL-3',
    'depends': ['demo_gov_hr_payroll_tax_eg', 'demo_gov_hr_payroll_insurance_eg', 'demo_gov_daftar55'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/hr_employee_salary_views.xml',
        'views/hr_payroll_reward_views.xml',
        'views/hr_payroll_disbursement_views.xml',
        'views/hr_payroll_run_views.xml',
        'views/hr_payroll_external_salary_views.xml',
        'views/hr_payroll_non_employee_reward_views.xml',
        'views/hr_payroll_allowance_increment_views.xml',
        'views/hr_payroll_tax_settlement_views.xml',
        'views/hr_payroll_run_menu.xml',
        'reports/form132_reports.xml',
        'reports/form132_template.xml',
        'reports/form132_bulk_reports.xml',
        'reports/form132_bulk_template.xml',
    ],
    'installable': True,
    'application': False,
}
