{
    'name': 'التقارير الحكومية — محافظة بورسعيد',
    'summary': 'مجموعة التقارير الحكومية الرسمية: مالية، محاسبية، إدارية',
    'version': '17.0.1.0.0',
    'category': 'Accounting/Egypt Government',
    'author': 'Paradise Integrated Solutions',
    'license': 'LGPL-3',
    'depends': [
        'base', 'mail', 'account',
        'port_said_daftar55',
        'port_said_daftar224',
        'port_said_commitment',
        'l10n_eg_auction',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/report_wizard_views.xml',
        'reports/gov_shared_layout.xml',
        'reports/report_actions.xml',
        'reports/rpt_01_daftar55_summary.xml',
        'reports/rpt_02_commitment_status.xml',
        'reports/rpt_03_budget_execution.xml',
        'reports/rpt_04_daftar224_daily.xml',
        'reports/rpt_05_auction_results.xml',
        'reports/rpt_06_lease_collection.xml',
        'reports/rpt_07_monthly_expenditure.xml',
        'reports/rpt_08_deductions_summary.xml',
        'reports/rpt_09_12_extra_reports.xml',
        'reports/rpt_10_trial_balance.xml',
        'reports/rpt_11_partner_ledger.xml',
        'reports/rpt_12_general_ledger.xml',
        'reports/rpt_13_budget_summary.xml',
        'reports/rpt_14_budget_variance.xml',
        'reports/rpt_15_budget_by_dept.xml',
        'reports/rpt_16_aging_suppliers.xml',
        'reports/rpt_17_aging_customers.xml',
        'reports/rpt_18_cash_bank.xml',
        'reports/rpt_19_advances_register.xml',
        'reports/rpt_20_guarantees_register.xml',
        'reports/rpt_21_stock_valuation.xml',
        'reports/rpt_chart_of_accounts.xml',

    ],
    'installable': True,
    'application': False,
}
