{
    'name': 'لوحة القيادة التنفيذية — الجهة الحكومية التجريبية',
    'version': '17.0.3.0.0',
    'category': 'الخدمات الحكومية التجريبية',
    'summary': 'Executive Dashboard for Demo Governorate — Real-time KPIs with Financial, Accounting & HR/Payroll sections',
    'author': 'Enterprise Solutions Demo',
    'license': 'LGPL-3',
    'depends': [
        'base', 'web', 'mail',
        'demo_branding',
        'procurement_committee',
        'stock_addition_permit',
        'stock_stocktaking_eg',
        'procurement_adjudication',
        'l10n_eg_custody',
        'l10n_eg_auction',
        'demo_gov_daftar55',
        'demo_gov_commitment',
        'general_ledger_ar',
        'demo_gov_hr_employee',
        'demo_gov_hr_leave',
        'demo_gov_hr_training',
        'demo_gov_hr_recruitment',
        'demo_gov_hr_performance',
        'demo_gov_hr_transfer',
        'demo_gov_hr_payroll_run',
        'demo_gov_hr_takaful',
        'demo_gov_hr_pension',
        'demo_gov_hr_disclosure',
        'demo_gov_hr_org_development',
        'demo_gov_hr_public_service',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/dashboard_views.xml',
        'views/dashboard_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
