{
    'name': 'لوحة القيادة التنفيذية — المحافظة التجريبية',
    'version': '17.0.2.0.0',
    'category': 'Dashboard/Egypt Government',
    'summary': 'Executive Dashboard for Demo Governorate — Real-time KPIs with Financial & Accounting section',
    'author': 'Enterprise Solutions Demo',
    'license': 'LGPL-3',
    'depends': [
        'base', 'web', 'mail',
        'procurement_committee',
        'stock_addition_permit',
        'stock_stocktaking_eg',
        'procurement_adjudication',
        'l10n_eg_custody',
        'l10n_eg_auction',
        'demo_gov_daftar55',
        'demo_gov_commitment',
        'general_ledger_ar',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/dashboard_views.xml',
        'views/dashboard_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
