{
    'name': 'السلف والضمانات البنكية — الجهة الحكومية التجريبية',
    'summary': 'FR-D-03: سلف مستديمة (62 ع.ح) + دفعات مقدمة + خطابات ضمان بنكية',
    'version': '17.0.2.0.0',
    'category': 'الخدمات الحكومية التجريبية/الحسابات',
    'author': 'Enterprise Solutions Demo',
    'license': 'LGPL-3',
    'depends': [
        'base', 'mail', 'account', 'hr', 'purchase',
        'demo_gov_daftar55',
        'demo_gov_commitment',
        'demo_gov_dossier',
        'demo_branding',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/advance_views.xml',
        'views/bank_guarantee_views.xml',
        'views/menu.xml',
        'reports/report_actions.xml',
        'reports/report_advance_form62.xml',
        'reports/report_bank_guarantee.xml',
        'reports/report_advances_register.xml',
    ],
    'installable': True,
    'application': False,
}
