# -*- coding: utf-8 -*-
"""
نموذج سجل تنظيف بيانات الاختبار
يسجل كل عملية تنظيف مع التفاصيل والنتائج
"""
import logging
from odoo import models, fields, api

_logger = logging.getLogger(__name__)

UAT_BATCH = 'UAT-AR-GOV-2026'

# Ordered list of transactional models to clean — dependency-aware order (children first)
TRANSACTIONAL_MODELS = [
    # Stock / Inventory
    ('stock.issue.permit',           'أذن الصرف',                  True),
    ('stock.move',                   'حركة المخزون',                True),
    ('stock.picking',                'استلام / إصدار مخزن',         True),
    ('port_said.warehouse_addition', 'إضافة مخزن',                  True),
    ('port_said.inspection_committee','لجنة الفحص',                 True),
    # Procurement & adjudication
    ('adjudication.supplier.line',   'بند مورد البت',               True),
    ('procurement.adjudication',     'البت الفني والمالي',          True),
    ('committee.member',             'عضو لجنة',                    True),
    ('procurement.committee',        'لجنة المشتريات',              True),
    ('port_said.requisition.line',   'بند طلب احتياج',             True),
    ('port_said.requisition',        'طلب احتياج',                  True),
    # Commitment
    ('port_said.commitment',         'ارتباط',                      True),
    # Dossier
    ('port_said.dossier.attachment', 'مرفق اضبارة',                 True),
    ('port_said.dossier',            'اضبارة',                      True),
    # Disbursement / payments
    ('port_said.daftar224',          'دفتر 224',                    True),
    ('port_said.daftar55',           'دفتر 55',                     True),
    ('port_said.payment_order',      'أمر دفع',                     True),
    ('port_said.outgoing_po',        'أمر دفع صادر',                True),
    ('port_said.surety',             'كفالة',                       True),
    ('port_said.cheque',             'شيك',                         True),
    ('port_said.cheque.book',        'دفتر شيكات',                  True),
    ('port_said.cash.folio',         'كشف نقدي',                    True),
    # Advances & guarantees
    ('port_said.bank.guarantee',     'ضمان بنكي',                   True),
    ('port_said.advance',            'سلفة',                        True),
    # Budget
    ('port_said.budget.line',        'بند موازنة',                  True),
    ('port_said.budget.plan',        'خطة موازنة',                  True),
    # Accounting journals generated by transactions
    ('account.move',                 'قيد محاسبي',                  True),
    # Forms / reports generated
    ('port_said.form69',             'استمارة 69',                  True),
    ('port_said.form75',             'استمارة 75',                  True),
    # Purchase orders (transactional)
    ('purchase.order.line',          'بند أمر شراء',                True),
    ('purchase.order',               'أمر شراء',                    True),
]


class UATCleanupLog(models.Model):
    _name = 'arabic.government.uat.cleanup.log'
    _description = 'سجل عمليات تنظيف بيانات الاختبار'
    _order = 'create_date desc'
    _inherit = ['mail.thread']

    name = fields.Char('المرجع', required=True, default='/', readonly=True)
    state = fields.Selection([
        ('draft', 'جديد'),
        ('done', 'مكتمل'),
        ('failed', 'فشل'),
    ], default='draft', string='الحالة', tracking=True)
    dry_run = fields.Boolean('تجربة جافة', default=True)
    cleanup_scope = fields.Selection([
        ('uat_only', 'بيانات UAT فقط'),
        ('all_transactions', 'جميع بيانات الحركات'),
    ], string='نطاق التنظيف', default='uat_only')
    notes = fields.Text('ملاحظات')
    result_summary = fields.Text('ملخص النتائج', readonly=True)
    error_message = fields.Text('رسالة الخطأ', readonly=True)
    total_deleted = fields.Integer('إجمالي المحذوفات', readonly=True)
    line_ids = fields.One2many('arabic.government.uat.cleanup.log.line', 'log_id', 'التفاصيل')
    create_uid = fields.Many2one('res.users', 'بواسطة', readonly=True)
    create_date = fields.Datetime('تاريخ العملية', readonly=True)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', '/') == '/':
                vals['name'] = self.env['ir.sequence'].next_by_code('uat.cleanup.log') or '/'
        return super().create(vals_list)


class UATCleanupLogLine(models.Model):
    _name = 'arabic.government.uat.cleanup.log.line'
    _description = 'تفصيل سجل التنظيف'
    _order = 'sequence'

    log_id = fields.Many2one('arabic.government.uat.cleanup.log', ondelete='cascade')
    sequence = fields.Integer(default=10)
    model_name = fields.Char('النموذج')
    arabic_name = fields.Char('الاسم العربي')
    record_count = fields.Integer('عدد السجلات')
    status = fields.Selection([
        ('ok', 'تم'),
        ('skipped', 'تخطى'),
        ('error', 'خطأ'),
    ], default='ok')
    message = fields.Char('رسالة')
