{
    'name': 'الأصول الثابتة — محافظة بورسعيد',
    'summary': 'إدارة وإهلاك الأصول الثابتة الحكومية — EAS #10 — متكامل مع العهد والمالية',
    'version': '17.0.1.0.0',
    'category': 'Accounting/Egypt Government',
    'author': 'Paradise Integrated Solutions',
    'license': 'LGPL-3',
    'depends': [
        'base', 'mail', 'account',
        'l10n_eg_custody',
        'port_said_daftar55',
        'port_said_commitment',
        'l10n_eg_auction',
        'general_ledger_ar',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/fixed_assets_security.xml',
        'data/asset_sequence.xml',
        'data/asset_category_data.xml',
        'views/asset_views.xml',
        'views/asset_category_views.xml',
        'views/asset_disposal_views.xml',
        'reports/report_actions.xml',
        'reports/report_asset_register.xml',
        'reports/report_asset_card.xml',
        'reports/report_depreciation_schedule.xml',
        'reports/report_disposal.xml',
        'views/asset_menu.xml',
    ],
    'installable': True,
    'application': False,
    'post_init_hook': 'post_init_hook',
}
