# -*- coding: utf-8 -*-
"""
نموذج سجل تنظيف بيانات الاختبار
يسجل كل عملية تنظيف مع التفاصيل والنتائج
"""
import logging
from odoo import models, fields, api

_logger = logging.getLogger(__name__)

UAT_BATCH = 'UAT-AR-GOV-2026'

# Ordered list of transactional models to clean — dependency-aware order (children first)
TRANSACTIONAL_MODELS = [
    # Stock / Inventory
    ('stock.issue.permit',            'أذن الصرف',                  True),
    ('stock.move',                    'حركة المخزون',                True),
    ('stock.picking',                 'استلام / إصدار مخزن',         True),
    ('demo_gov.warehouse.addition',   'إضافة مخزن',                  True),
    ('demo_gov.inspection.committee', 'لجنة الفحص',                  True),
    # Procurement & adjudication
    ('adjudication.supplier.line',    'بند مورد البت',               True),
    ('procurement.adjudication',      'البت الفني والمالي',          True),
    ('committee.member',              'عضو لجنة',                    True),
    ('procurement.committee',         'لجنة المشتريات',              True),
    ('demo_gov.requisition.line',     'بند طلب احتياج',              True),
    ('demo_gov.requisition',          'طلب احتياج',                   True),
    # Commitment
    ('demo_gov.commitment',           'ارتباط',                       True),
    # Dossier
    ('demo_gov.dossier.attachment',   'مرفق اضبارة',                  True),
    ('demo_gov.dossier',              'اضبارة',                        True),
    # Disbursement / payments
    ('demo_gov.daftar224',            'دفتر 224',                      True),
    ('demo_gov.daftar55',             'دفتر 55',                       True),
    ('demo_gov.payment_order',        'أمر دفع',                       True),
    ('demo_gov.outgoing_po',          'أمر دفع صادر',                  True),
    ('demo_gov.surety',               'كفالة',                          True),
    ('demo_gov.cheque',               'شيك',                            True),
    ('demo_gov.cheque.book',          'دفتر شيكات',                    True),
    ('demo_gov.cash.folio',           'كشف نقدي',                      True),
    # Advances & guarantees
    ('demo_gov.bank.guarantee',       'ضمان بنكي',                     True),
    ('demo_gov.advance',              'سلفة',                           True),
    # Budget
    ('demo_gov.budget.line',          'بند موازنة',                    True),
    ('demo_gov.budget.plan',          'خطة موازنة',                    True),
    # Accounting journals generated by transactions
    ('account.move',                  'قيد محاسبي',                    True),
    # Forms / reports generated
    ('demo_gov.form69',               'استمارة 69',                    True),
    ('demo_gov.form75',               'استمارة 75',                    True),
    # Purchase orders (transactional)
    ('purchase.order.line',           'بند أمر شراء',                  True),
    ('purchase.order',                'أمر شراء',                      True),
]


class UATCleanupLog(models.Model):
    _name = 'arabic.government.uat.cleanup.log'
    _description = 'سجل عمليات تنظيف بيانات الاختبار'
    _order = 'create_date desc'
    _inherit = ['mail.thread']

    name = fields.Char('المرجع', required=True, default='/', readonly=True)
    state = fields.Selection([
        ('draft', 'جديد'),
        ('done', 'مكتمل'),
        ('failed', 'فشل'),
    ], default='draft', string='الحالة', tracking=True)
    dry_run = fields.Boolean('تجربة جافة', default=True)
    cleanup_scope = fields.Selection([
        ('uat_only', 'بيانات UAT فقط'),
        ('all_transactions', 'جميع بيانات الحركات'),
    ], string='نطاق التنظيف', default='uat_only')
    notes = fields.Text('ملاحظات')
    result_summary = fields.Text('ملخص النتائج', readonly=True)
    error_message = fields.Text('رسالة الخطأ', readonly=True)
    total_deleted = fields.Integer('إجمالي المحذوفات', readonly=True)
    line_ids = fields.One2many('arabic.government.uat.cleanup.log.line', 'log_id', 'التفاصيل')
    create_uid = fields.Many2one('res.users', 'بواسطة', readonly=True)
    create_date = fields.Datetime('تاريخ العملية', readonly=True)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', '/') == '/':
                vals['name'] = self.env['ir.sequence'].next_by_code('uat.cleanup.log') or '/'
        return super().create(vals_list)


class UATCleanupLogLine(models.Model):
    _name = 'arabic.government.uat.cleanup.log.line'
    _description = 'تفصيل سجل التنظيف'
    _order = 'sequence'

    log_id = fields.Many2one('arabic.government.uat.cleanup.log', ondelete='cascade')
    sequence = fields.Integer(default=10)
    model_name = fields.Char('النموذج')
    arabic_name = fields.Char('الاسم العربي')
    record_count = fields.Integer('عدد السجلات')
    status = fields.Selection([
        ('ok', 'تم'),
        ('skipped', 'تخطى'),
        ('error', 'خطأ'),
    ], default='ok')
    message = fields.Char('رسالة')
