{
    'name': 'التقارير الحكومية الثمانية — SSRS Wave 3',
    'summary': 'C-03: remaining 6 of the 8 official government SSRS forms (Form 5 and Form 15 ship in their own modules)',
    'version': '17.0.1.0.0',
    'category': 'الخدمات الحكومية التجريبية/الموارد البشرية',
    'author': 'Enterprise Solutions Demo',
    'license': 'LGPL-3',
    'depends': [
        'demo_gov_hr_leave',
        'demo_gov_hr_performance',
        'demo_gov_hr_transfer',
        'demo_gov_hr_training',
        'demo_gov_hr_disclosure',
    ],
    'data': [
        'reports/ssrs01_work_injury_reports.xml',
        'reports/ssrs01_work_injury_template.xml',
        'reports/ssrs02_leave_certificate_reports.xml',
        'reports/ssrs02_leave_certificate_template.xml',
        'reports/ssrs03_performance_reports.xml',
        'reports/ssrs03_performance_template.xml',
        'reports/ssrs06_transfer_reports.xml',
        'reports/ssrs06_transfer_template.xml',
        'reports/ssrs07_training_needs_reports.xml',
        'reports/ssrs07_training_needs_template.xml',
        'reports/ssrs08_disclosure_status_reports.xml',
        'reports/ssrs08_disclosure_status_template.xml',
    ],
    'installable': True,
    'application': False,
}
