{
    'name': 'استمارة 50 ع.ح — طبقة الطباعة الرسمية',
    'summary': 'طبقة طباعة رسمية مطابقة للنموذج الحكومي فوق دفتر 55 ع.ح',
    'version': '17.0.1.0.2',
    'category': 'Accounting/Egypt Government',
    'author': 'Paradise Integrated Solutions',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'account',
        'purchase',
        'port_said_daftar55',
        'port_said_daftar224',
        'port_said_dossier',
        'port_said_commitment',
        'stock_addition_permit',
        'port_said_scm_purchase_bridge',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security_groups.xml',
        'data/paperformat.xml',
        'views/form50_print_views.xml',
        'views/form50_menu.xml',
        'wizard/reprint_wizard_views.xml',
        'reports/report_actions.xml',
        'reports/form50_preview_template.xml',
        'reports/form50_final_template.xml',
    ],
    'installable': True,
    'application': False,
    'post_migrate': 'port_said_form50_print.models.form50_print.post_migrate',
}
