{
    'name': 'الديوان العام - المحافظة التجريبية — تنظيم القوائم',
    'summary': 'Unified single-tab menu structure for Demo Governorate',
    'version': '17.0.6.0.0',
    'author': 'Enterprise Solutions Demo',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'demo_gov_daftar55',
        'demo_gov_daftar224',
        'demo_gov_commitment',
        'demo_gov_dossier',
        'l10n_eg_auction',
        'procurement_committee',
        'c13_tax_xml_export',
        'demo_gov_reports',
        'demo_gov_fixed_assets',
        'demo_gov_scm_issue',
        'demo_gov_stock_finance_bridge',
        'demo_gov_advances',
        'demo_gov_budget_planning',
        'demo_gov_acct_reports',
        'l10n_eg_eta_invoice',
    ],
    'data': [
        'views/menu_structure.xml',
        'views/menu_dashboard.xml',
        'views/menu_accts.xml',
        'views/menu_accts_wave2.xml',
        'views/menu_purchase.xml',
        'views/menu_auctions.xml',
        'views/menu_inventory.xml',
        'views/menu_reports.xml',
    ],
    'installable': True,
    'application': False,
}
