{
    'category': 'الديوان العام',
    'name': 'الديوان العام - محافظة بورسعيد — تنظيم القوائم',
    'summary': 'Unified single-tab menu structure for Port Said Governorate',
    'version': '17.0.6.0.0',
    'author': 'Paradise Integrated Solutions',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'port_said_daftar55',
        'port_said_daftar224',
        'port_said_commitment',
        'port_said_dossier',
        'l10n_eg_auction',
        'procurement_committee',
        'c13_tax_xml_export',
        'port_said_reports',
        'port_said_fixed_assets',
        'port_said_scm_issue',
        'port_said_stock_finance_bridge',
        'port_said_advances',
        'port_said_budget_planning',
        'port_said_acct_reports',
        'l10n_eg_eta_invoice',
    ],
    'data': [
        'views/menu_structure.xml',
        'views/menu_dashboard.xml',
        'views/menu_accts.xml',
        'views/menu_accts_wave2.xml',
        'views/menu_purchase.xml',
        'views/menu_auctions.xml',
        'views/menu_inventory.xml',
        'views/menu_reports.xml',
    ],
    'installable': True,
    'application': False,
}
